- name: Build Flipper Application Package (.fap)
  uses: flipperdevices/flipperzero-ufbt-action@v0.1.4
  with:
    app-dir: '.'  # Path to application's source code (if not the root of the repository)
    task: 'build'  # Task to run. Valid values: 'build', 'lint', 'setup'
    ufbt-args: '-s'  # Extra arguments to pass to 'ufbt' for build and lint tasks
    skip-setup: false  # Skip ufbt setup. Useful for multiple invocations of the action
    sdk-channel: ''  # Release channel to use. Matches argument "--channel" for ufbt update
    sdk-branch: ''  # Branch to use for updates. Matches argument "--branch" for ufbt update
    sdk-index-url: ''  # Index URL to use for updates. Matches argument "--index-url" for ufbt update
    sdk-file: ''  # Path to SDK archive. Matches argument "--local" for ufbt update
    sdk-url: ''  # URL to SDK archive. Matches argument "--url" for ufbt update
    sdk-hw-target: ''  # Hardware target to use. Matches argument "--hw-target" for ufbt update
    ufbt-version: 'latest'  # ufbt version to use. Can be 'latest', 'prerelease', or a specific version
